# 스프링 설정
spring:
  datasource:
    url: jdbc:mariadb://175.197.69.42:3307/malldb?useUnicode=true&character_set_server=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    hikari:
      maximum-pool-size: 10        # 연결 풀 크기 조정 (필요에 맞게 조절)
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect   # MariaDB 특성에 맞는 Dialect 추가

##servlet 설정은 보통 Spring과 동등한 레벨에 위치해야 SpringBoot가 제대로 이를 인식한다.
servlet:
  multipart:
    max-request-size: 30MB
    max-file-size: 10MB

org:
  zerock:
    upload:
      path: upload

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE        
    org.springframework.security.web: TRACE


#JPA ddl-auto 설정
# create: 기존 테이블 삭제 후, 다 생성(DROP + CREATE)
# create-drop: create와 같으나 종료 시점에 테이블 DROP
# update: 변경분만 반영(개발 환경에서만 사용할 것)
# validate: 엔티티와 테이블이 정상적인지만 확인
# none: DDL 처리에 관여하지 안음.

